[package]
name = "maybenot"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Tobias Pulls <tobias@pulls.name>"]
homepage = "http://maybenot.io/"
repository = "https://github.com/maybenot-io/maybenot-rs"
description = "a library for running state machines that pad and/or block network traffic to hide patterns"

[dependencies]
rand="0.8.5"
byteorder="1.4.3"
simple-error = "0.3.0"
hex = "0.4.3"
libflate = "2.0.0"
ring = "0.16.20"
rand_distr = "0.4.3"
serde = {version = "1.0.185", features = ["derive"]}
